# Generated by Django 5.1.7 on 2026-08-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('prompt', models.TextField(help_text='The main textual story prompt entered by the user')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('final_video', models.FileField(blank=True, help_text='The fully stitched animation video file', null=True, upload_to='animations/completed/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.PositiveIntegerField()),
                ('prompt', models.TextField(help_text='Visual prompt for this specific scene')),
                ('narration_text', models.TextField(help_text='Speech or narration text overlay for this scene')),
                ('image_file', models.ImageField(blank=True, help_text='Generated image asset for the scene', null=True, upload_to='animations/scenes/images/')),
                ('video_file', models.FileField(blank=True, help_text='Generated video clip for the scene', null=True, upload_to='animations/scenes/videos/')),
                ('duration', models.FloatField(default=4.0, help_text='Duration of this scene in seconds')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING_ASSETS', 'Generating Assets'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='stories.story')),
            ],
            options={
                'ordering': ['story', 'scene_number'],
            },
        ),
    ]
