# Generated by Django 5.1.7 on 2026-08-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='document_file',
            field=models.FileField(blank=True, help_text='Uploaded story script file (PDF, DOCX, TXT)', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='story',
            name='source_filename',
            field=models.CharField(blank=True, help_text='Original filename of the uploaded document', max_length=255),
        ),
    ]
