# Generated by Django 5.1.7 on 2026-08-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_document_file_story_source_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='animation_prompt',
            field=models.TextField(blank=True, help_text='Prompt detailing camera movement or video motion', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='camera_angle',
            field=models.CharField(blank=True, help_text='Camera shot type and angle', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='characters',
            field=models.TextField(blank=True, help_text='Characters involved in this scene', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of scene action', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='environment',
            field=models.TextField(blank=True, help_text='Setting or location details', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='image_prompt',
            field=models.TextField(blank=True, help_text='Detailed visual prompt used for image rendering', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='lighting',
            field=models.TextField(blank=True, help_text='Lighting description', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='mood',
            field=models.TextField(blank=True, help_text='Emotional tone of the scene', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the scene', max_length=255, null=True),
        ),
    ]
