# Generated by Django 5.1.7 on 2026-08-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_scene_animation_prompt_scene_camera_angle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='image_generation_time',
            field=models.FloatField(blank=True, help_text='Time taken to generate the image in seconds', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='image_model',
            field=models.CharField(blank=True, help_text='AI model name used to generate this image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='image_seed',
            field=models.BigIntegerField(blank=True, help_text='Generation seed value used for reproducibility', null=True),
        ),
    ]
