# Generated by Django 5.1.7 on 2026-08-08 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_scene_image_generation_time_scene_image_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('video_file', models.FileField(blank=True, help_text='Locally downloaded generated video file', null=True, upload_to='animations/scenes/videos/')),
                ('external_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('fps', models.IntegerField(blank=True, null=True)),
                ('generation_time', models.FloatField(blank=True, help_text='Total API execution time in seconds', null=True)),
                ('api_response', models.TextField(blank=True, help_text='Raw API JSON response text', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_videos', to='stories.scene')),
            ],
        ),
    ]
