# Generated by Django 5.1.7 on 2026-08-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, help_text='Celery task UUID', max_length=255, null=True)),
                ('step', models.CharField(choices=[('STORY_INITIALIZATION', 'Story Initialization'), ('SCRIPT_GENERATION', 'Script & Scenes Generation'), ('IMAGE_GENERATION', 'Image Assets Generation'), ('VIDEO_GENERATION', 'Video Clip Generation'), ('FFMPEG_STITCHING', 'FFmpeg Video Stitching'), ('COMPLETED', 'Pipeline Completed'), ('FAILED', 'Pipeline Failed')], max_length=50)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('log_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stories.story')),
            ],
            options={
                'ordering': ['story', 'started_at'],
            },
        ),
    ]
