# Generated by Django 5.1.7 on 2026-08-07 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('stories', '0002_story_document_file_story_source_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('prompt', models.TextField()),
                ('response_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_seconds', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to='stories.story')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
