# Generated by Django 5.1.7 on 2026-08-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_llmapilog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerunlog',
            name='step',
            field=models.CharField(choices=[('STORY_INITIALIZATION', 'Story Initialization'), ('SCRIPT_GENERATION', 'Script & Scenes Generation'), ('DIRECT_VIDEO_GENERATION', 'Direct Video Generation'), ('NARRATION', 'Narration Track Generation'), ('BACKGROUND_MUSIC', 'Background Music Integration'), ('FFMPEG_STITCHING', 'FFmpeg Video Stitching'), ('COMPLETED', 'Pipeline Completed'), ('FAILED', 'Pipeline Failed')], max_length=50),
        ),
    ]
